language: ruby
before_install:
  - 'gem install travis'
script:
  - find . -type f -iname '*.yml' -not \( -path './.github/*' \)  -exec sh -c 'for n; do travis lint --skip-completion-check -x "$n" || exit 1; done' sh {} +
