name: 'Regenerate version lists'
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ljharb/actions/node/install@main
              with:
                node-version: lts/*
            - run: |
                node node/generate.mjs
                if [ -n "$(git status --porcelain)" ]; then
                    git config user.name ${{ secrets.USERNAME }}
                    git config user.email ${{ secrets.EMAIL }}
                    git commit -am '[node] update version lists from nodejs.org/dist'
                    git push
                fi
